
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - streaming.projectriff.io
  resources:
  - processors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.projectriff.io
  resources:
  - processors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - streaming.projectriff.io
  resources:
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.projectriff.io
  resources:
  - streams/status
  verbs:
  - get
  - patch
  - update
