
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: adapters.knative.projectriff.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    type: string
  group: knative.projectriff.io
  names:
    categories:
    - riff
    kind: Adapter
    plural: adapters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Adapter is the Schema for the adapters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AdapterSpec defines the desired state of Adapter
          properties:
            build:
              description: Build resolves the image from a build resource. As the
                target build produces new images, they will be automatically rolled
                out to the handler.
              properties:
                applicationRef:
                  description: ApplicationRef references an application in this namespace.
                  type: string
                containerRef:
                  description: ContainerRef references a container in this namespace.
                  type: string
                functionRef:
                  description: FunctionRef references an application in this namespace.
                  type: string
              type: object
            target:
              description: Target Knative resource
              properties:
                configurationRef:
                  description: ConfigurationRef references a Knative Configuration
                    in this namespace.
                  type: string
                serviceRef:
                  description: ServiceRef references a Knative Service in this namespace.
                  type: string
              type: object
          required:
          - build
          - target
          type: object
        status:
          description: AdapterStatus defines the observed state of Adapter
          properties:
            conditions:
              description: Conditions the latest available observations of a resource's
                current state.
              items:
                description: 'Conditions defines a readiness condition for a Knative
                  resource. See: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties'
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transitioned from one status to another. We use VolatileTime
                      in place of metav1.Time to exclude this from creating equality.Semantic
                      differences (all other things held constant).
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  severity:
                    description: Severity with which to treat failures of this type
                      of condition. When this is not specified, it defaults to Error.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            latestImage:
              description: LatestImage is the most recent image resolved from the
                build and applied to the target
              type: string
            observedGeneration:
              description: ObservedGeneration is the 'Generation' of the Service that
                was last processed by the controller.
              format: int64
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
